theme: jekyll-theme-minimal
title: dayyoung.github.io/qrturn
description: HTML5 QR Web Application
logo: https://dayyoung.github.io/qrturn/qrturn.png
port: 80
google_analytics : G-XW3LSKJQG4
url : https://dayyoung.github.io/qrturn

